### ISSUE TITLE
Proxyの有無にかかわらず動くように修正する

### ISSUE THREAD

**Issue by yamadashizuka** [yada-ITA/tora#1]
今現在はProxyがある環境でしか動かないってことなので、どっちでも動くようにしてほしいです。

**Comment by yada-ITA** [comment]
proxyの設定は、環境変数で設定するようにしているので、環境変数PROXY_PATHに
設定がない場合は、proxyが無いものとして処理するようにします。

**Comment by yada-ITA** [comment]
Herokuへのアップまで完了したので、このissueはクローズします。
